# Site settings
timezone: Asia/Seoul
title: JIMIN JEON
sub-title: Software Engineer
email: haven04@gmail.com
description: > 
    Personal website of Jimin Jeon, a Korea-based software engineer.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jiminis.me" # the base hostname & protocol for your site

# Build settings
# category-list: [projects, editors, math, unix]
markdown: kramdown

gems: ['jekyll-redirect-from']

category-projects: 'projects'

excerpt_separator: "<!-- more -->"